version: 2.1

executors:
  nodejs_executor:
    docker:
      - image: circleci/node:13.8.0

jobs:
  build:
    executor: nodejs_executor
    steps:
      - checkout
      - run:
          name: Install Packages
          command: npm i
      - save_cache:
          name: Saving Files to Cache
          key: v1-shortlink-1
          paths:
            - ./node_modules
      - run:
          name: Linting
          command: |
            pwd
            ls -lah
            npm run lint

  test:
    executor: nodejs_executor
    steps:
      - checkout
      - restore_cache:
          name: Restore Cache
          key: v1-shortlink-1
      - run:
          name: Run Tests
          command: |
            pwd
            ls -lah
            npm run test

  analyze:
    executor: nodejs_executor
    steps:
      - checkout
      - restore_cache:
          name: Restore Cache
          key: v1-shortlink-1
      - run:
          name: Run Analysis
          command: |
            pwd
            ls -lah
            npm audit

workflows:
  node_workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - analyze:
          requires:
            - test
